PR #4
apostrophecms/code-upgrader pull request #14
Opened 2021-11-19 20:53 UTC by boutell

2021-11-19 22:35 UTC, abea requested changes

2021-11-19 22:35 UTC, abea commented on README.md
> +#### The `lint` command
This is meant to be an overview of the tool as a whole. The lint command material should be at the start of  the "Linting the A2 codebase" section.

2021-11-19 22:35 UTC, abea commented on README.md
> +#### The `upgrade` command
Similarly, this material should be at the start of the "Running the code upgrade" section below.

2021-11-19 22:35 UTC, abea commented on README.md
> +- Moving code in `construct`, and `afterConstruct` that can't otherwise be converted into appropriate A3 module functions.
I did see `beforeConstruct` material moved to `beforeSuperClass`. has that changed?

2021-11-19 22:35 UTC, abea commented on README.md
> +## Pre-alpha options
This should be a third level heading before the reset bit.

2021-11-19 22:35 UTC, abea commented on README.md
> +The upgrade command has experimental support for inlining certain `require`-d files in order to discover methods, handlers, etc. inside those files as well. This generally will not work well unless r
For clarity I suggest:

> ... support for inlining certain module configuration included with `require` statements in order to discover...

2021-11-19 22:35 UTC, abea commented on README.md
> +The upgrade command has experimental support for inlining certain `require`-d files in order to discover methods, handlers, etc. inside those files as well. This generally will not work well unless r
"confine" => "limit"

2021-11-19 22:35 UTC, abea commented on README.md
> +## Pre-alpha options
I don't think we need to specify that they are pre-alpha. Simply "Options." As it evolves out of alpha the documentation will change.

2021-11-22 16:42 UTC, abea requested changes
a few bits to clean up

2021-11-22 16:42 UTC, abea commented on README.md
> +This module can also carry out some upgrades automatically. While this is a great feature, keep in mind that not every module and project is a good candidate for automated code upgrading as there are
Typo "featureworks"

2021-11-22 16:42 UTC, abea commented on README.md
> +There are also many needed changes that the upgrade command cannot handle on its own. So a successful upgrade will always involve reviewing the output of the linting feature,  as well as the Apostrop
two spaces after "the linting feature,"

2021-11-22 16:42 UTC, abea commented on README.md
> +modifications that likely need to be made to be compatible with A3. The lint command will work well with basically all projects and detects many issues. Here are just a few examples of what the linte
This is duplicated from above.

2021-11-22 16:42 UTC, abea commented on README.md
> +- Converting field schemas, columns, and similarly structured features to the A3 "cascade" configuration structure, if the existing module follows the structure of our A2 example projects closely eno
I think we should avoid "our." In the original I'd worded it as "the official A2 sample projects" to not speak from a place of ownership.

2021-11-22 16:42 UTC, abea commented on README.md
> +## Automatically upgarding the A2 codebase
"upgarding"

2021-11-22 17:13 UTC, abea requested changes
one missed text thing. Also the ESLint errs

2021-11-22 17:13 UTC, abea commented on README.md
> +- Converting field schemas, columns, and similarly structured features to the A3 "cascade" configuration structure, if the existing module follows the structure of our A2 example projects closely eno
You got the one below. Another on L42.

2021-11-22 17:19 UTC, boutell commented
I think you said there is still one text duplication issue somehow but I can't find it?

2021-11-22 17:20 UTC, boutell commented
(Line numbers have changed)

2021-11-22 17:20 UTC, abea commented
@boutell It's the other "our A2 example projects"

2021-11-22 17:59 UTC, abea approved these changes

2021-11-22 18:14 UTC, merged